/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AstroToolsRouteImport } from './routes/astro-tools'
import { Route as MapasRouteImport } from './routes/mapas'
import { Route as MentoriaRouteImport } from './routes/mentoria'
import { Route as PlanosRouteImport } from './routes/planos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroToolsRoute = AstroToolsRouteImport.update({
  id: '/astro-tools',
  path: '/astro-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasRoute = MapasRouteImport.update({
  id: '/mapas',
  path: '/mapas',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriaRoute = MentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astro-tools': typeof AstroToolsRoute
  '/mapas': typeof MapasRoute
  '/mentoria': typeof MentoriaRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astro-tools': typeof AstroToolsRoute
  '/mapas': typeof MapasRoute
  '/mentoria': typeof MentoriaRoute
  '/planos': typeof PlanosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astro-tools': typeof AstroToolsRoute
  '/mapas': typeof MapasRoute
  '/mentoria': typeof MentoriaRoute
  '/planos': typeof PlanosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/astro-tools' | '/mapas' | '/mentoria' | '/planos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/astro-tools' | '/mapas' | '/mentoria' | '/planos'
  id: '__root__' | '/' | '/astro-tools' | '/mapas' | '/mentoria' | '/planos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstroToolsRoute: typeof AstroToolsRoute
  MapasRoute: typeof MapasRoute
  MentoriaRoute: typeof MentoriaRoute
  PlanosRoute: typeof PlanosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro-tools': {
      id: '/astro-tools'
      path: '/astro-tools'
      fullPath: '/astro-tools'
      preLoaderRoute: typeof AstroToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas': {
      id: '/mapas'
      path: '/mapas'
      fullPath: '/mapas'
      preLoaderRoute: typeof MapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoria': {
      id: '/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof MentoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstroToolsRoute: AstroToolsRoute,
  MapasRoute: MapasRoute,
  MentoriaRoute: MentoriaRoute,
  PlanosRoute: PlanosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
